# Generated by Django 2.2.6 on 2020-09-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=160)),
                ('author', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=100)),
            ],
        ),
    ]
