# Generated by Django 2.2.6 on 2019-11-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(default='http://#', max_length=20),
        ),
    ]
