# Generated by Django 2.2.6 on 2019-11-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_job_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('start', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
            ],
        ),
    ]
