# Generated by Django 2.2.6 on 2020-09-14 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumbotron',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
