# Generated by Django 2.2.6 on 2019-11-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(max_length=20),
        ),
    ]
