# Generated by Django 2.2.6 on 2020-09-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20200914_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='instagram',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='bar',
            name='stackexchange',
            field=models.URLField(default='#', max_length=254),
        ),
        migrations.AddField(
            model_name='bar',
            name='twitter',
            field=models.URLField(default='#'),
        ),
    ]
