# Generated by Django 2.2.13 on 2020-09-14 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20200914_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bar',
            name='github',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='instagram',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='linkedin',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='stackexchange',
            field=models.URLField(blank=True, default='#', max_length=254),
        ),
        migrations.AlterField(
            model_name='bar',
            name='twitter',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
